### ISSUE TITLE
Метод public boolean containsGame не находит игру, даже если она есть, и возвращает false

### ISSUE THREAD

**Issue by UralHawkies** [UralHawkies/JavaTeam#9]
## Описание:
Метод public boolean containsGame(Game game) в классе GameStore не находит игру, даже если она добавлена, и возвращает false

## Локация дефекта:
https://github.com/UralHawkies/JavaTeam/blob/44ce89bebbf0f11be52dad802751f93fb4896372/src/main/java/ru/netology/GameStore.java#L32-L39

## Шаги воспроизведения:
1. Открыть [код программы](https://github.com/UralHawkies/JavaTeam/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA
1. Запустить тест public void shouldAddGame()
1. Посмотреть результат теста

*Ожидаемый результат:*
Тест успешно проходит. Добавленная игра находится.

*Фактический результат:*
Тест не проходит. Метод store.containsGame(game) не находит игру.

## Скриншот:
![image](https://user-images.githubusercontent.com/105659020/186212647-b0d9d931-a3c5-4dcb-952c-415287530ca0.png)

## Окружение:
**ОС:** Windows 10 Pro
**IDE:** IntelliJ IDEA 2022.1.4 (Community Edition)
**Java:** Open JDK 11

**Comment by Kislitsina-Maria** [comment]
Тест проходит
